# Generated by Django 5.0.2 on 2024-03-08 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.IntegerField()),
                ('tech', models.IntegerField(default=0)),
                ('etc', models.IntegerField(default=0)),
                ('art', models.IntegerField(default=0)),
                ('sports', models.IntegerField(default=0)),
                ('academic', models.IntegerField(default=0)),
                ('overall', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
