# Generated by Django 5.0.2 on 2024-03-01 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='desc',
            field=models.CharField(default='desc', max_length=10000),
        ),
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.CharField(default='img', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
