# Generated by Django 5.0.2 on 2024-03-03 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_posts_category_posts_date_posts_desc_posts_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='branch',
            field=models.CharField(default='cse', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='registration_number',
            field=models.CharField(default='2001335012', max_length=255),
            preserve_default=False,
        ),
    ]
