# Generated by Django 5.0.2 on 2024-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_ban_users_branch_users_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='branch',
            field=models.CharField(default='cse', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_number',
            field=models.CharField(default='0000000000', max_length=255),
        ),
    ]
